[package]
name = "nila"
version = "0.1.0"
authors = ["Eino <e.i.korte@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term = "0.6.1"
glob = "0.3.0"
